In [4]:


import numpy as np
from scipy.spatial.transform import Rotation as R

import math as Math

#[ 0, 0, 0, 1 ]
q1 = R.from_quat((0, 0, 1, 0))
print(q1.as_euler('xyz', degrees=True))
q2 = R.from_quat((0, 0, 1, 0))
print(q2.as_euler('xyz', degrees=True))
q4 = R.from_quat((0.2588192952625891, -0.9659257592588453, 9.939400520544888e-13, 2.105078795953449e-12))
print(q4.as_euler('xyz', degrees=True))
#subtract
q3 = q1 * q2.inv()
q5 = q1 * q4.inv()

#print euler xyz
np.set_printoptions(suppress=True)
print(f"q3: {q3.as_euler('xyz', degrees=True)}")

[  0.   0. 180.]
[  0.   0. 180.]
[-180.           -0.         -149.99997032]
q3: [0. 0. 0.]


In [ ]:
from plunger import Plunger

serial_handler = Plunger("COM13", 115200)
serial_handler.start()

while True:
    if not serial_handler.output.empty():
        json_data = serial_handler.output.get()
        print(json_data)

In [ ]:

lara.robot.turn_on_jog(
    jog_velocity=[0, 0, speed, 0, 0, 0],
    jog_type='Cartesian'
)
interval_s = interval_ms / 1000
for i in range(iterations):
    lara.robot.jog(set_jogging_external_flag=1)
lara.robot.turn_off_jog()